package com.sorianotapia.screens;

public enum ScreenName {
    SCREEN_HEADER,
    MAIN_SELECTION,
    SELECT_DRUG_TO_BUY, SELECT_QTY_TO_BUY, HOLD_EXCEEDED, CASH_EXCEEDED,
    SELECT_DRUG_TO_SELL, SELECT_QTY_TO_SELL, STASH_EXCEEDED,
    TRAVEL, TRAVEL_TOO_EXPENSIVE, TRAVEL_OK, TRAVEL_NOT_OK,
    LOAN_SHARK,
    BORROW_MONEY, BORROW_MONEY_TOO_MUCH, BORROW_MONEY_TOO_LITTLE, BORROW_MONEY_OK, BORROW_MONEY_NOT_OK,
    PAY_BACK_MONEY, PAY_BACK_IN_FULL, PAY_BACK_PARTIALLY, PAY_BACK_ZERO, PAY_BACK_TOO_MUCH,
    BANK_OPERATION_SELECTION,
    DEPOSIT_MONEY, DEPOSIT_EXCEEDED,
    WITHDRAW_MONEY, WITHDRAW_LIMIT_EXCEEDED,
    GO_TO_HOSPITAL, HEALED, NOT_HEALED, NO_CASH_FOR_HEALING,
    RELAX,
    EVENT_PRICE_INCREASE, EVENT_PRICE_DECREASE,
    ROB_ALL_MONEY, ROB_ALL_MONEY_NO_OK,
    ROB_ALL_STUFF, ROB_ALL_STUFF_NO_OK,
    BUY_STUFF_CARRIER, BUY_STUFF_CARRIER_OK, BUY_STUFF_CARRIER_NO,
    BUY_ARM, BUY_ARM_OK, BUY_ARM_NO_OK, NO_MONEY;
    }
