package com.sorianotapia;

public enum MethodAnswers {
    INSUFFICIENT_MONEY, INSUFFICIENT_STASH, SUCCESS, INSUFFICIENT_HOLD, QUANTITY_ZERO, SAME_ORIGIN_AND_DESTINATION, QUANTITY_NOT_WORTH_THE_FUSS, DEBT_CANCELLED, PARTIAL_PAYBACK_OK, MINIMUM_LOAN_NOT_REACHED, MAXIMUM_CREDIT_EXCEEDED, CURRENT_CREDIT_EXCEEDED;
}
