package com.sorianotapia.events;

public enum EventName {
    BUY_ARM_EVENT, BUY_STUFF_CARRIER_EVENT, GAME_OVER_EVENT, MONEY_ROBBERY_EVENT, POLICE_COMBAT_EVENT,
    PRICE_DECREASE_EVENT, PRICE_INCREASE_EVENT, RECLAIM_DEBT_EVENT, STUFF_ROBBERY_EVENT, DAILY_PRICE_UPDATE_EVENT;
    int frequency;
}
